#!/usr/bin/env python3
"""Compile an envelope bank into a C header the Teensy can read from flash.

    .venv-vocoder/bin/python tools/envelopes_to_header.py \
        songs/amazing_grace.envelopes.npz -o src/voice/envelopes_amazing_grace.h

Band gains and voicing are quantised to uint8. That is not a shortcut: the
renderer's gains are 0..1 and the Audio Library's mixer resolution is well
under 1/255, so the quantisation is inaudible while cutting the table to a
quarter of its float size. 14 bands + 1 voicing byte per 10 ms frame = 15
bytes per frame, about 1.5 kB per second of singing.

Emits a syllable index so the firmware can look up a note's envelope by name,
plus the onset/nucleus/coda split so it can apply the time-stretch policy.
"""

import argparse
import pathlib

import numpy as np


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("npz", type=pathlib.Path)
    ap.add_argument("-o", "--out", type=pathlib.Path, required=True)
    ap.add_argument("--name", default=None, help="C identifier stem")
    args = ap.parse_args(argv)

    z = np.load(args.npz, allow_pickle=False)
    sylls = [str(s) for s in z["syllables"]]
    stem = args.name or args.npz.stem.replace(".envelopes", "").replace("-", "_")

    frames, index, total = [], [], 0
    for s in sylls:
        b = z[f"{s}/bands"]; v = z[f"{s}/voi"]; ns, ne = (int(x) for x in z[f"{s}/seg"])
        n = b.shape[1]
        q = np.clip(np.rint(b*255), 0, 255).astype(np.uint8)      # 14 bands
        qv = np.clip(np.rint(v*255), 0, 255).astype(np.uint8)     # + voicing
        for i in range(n):
            frames.append(list(q[:, i]) + [int(qv[i])])
        index.append((s, total, n, ns, ne))
        total += n

    L = []
    L.append("// Generated by tools/envelopes_to_header.py — do not edit.")
    L.append(f"// Source: {args.npz.name}")
    L.append("//")
    L.append("// 14 band gains + 1 voicing byte per 10 ms frame, uint8. The gains are")
    L.append("// 0..1 in the renderer and the mixer's resolution is well under 1/255,")
    L.append("// so this quantisation is inaudible and a quarter of the float size.")
    L.append("#pragma once")
    L.append("")
    L.append("#include <Arduino.h>")
    L.append("")
    L.append("struct VocEnvelope {")
    L.append("  const char *syllable;")
    L.append("  uint16_t offset;    // first frame in the frame table")
    L.append("  uint16_t frames;    // total frames")
    L.append("  uint16_t nucleusStart;  // consonant head ends here")
    L.append("  uint16_t nucleusEnd;    // vowel ends, coda begins")
    L.append("};")
    L.append("")
    L.append(f"// {total} frames, {total*15} bytes of frame data")
    L.append(f"const uint8_t {stem}_frames[][15] PROGMEM = {{")
    for f in frames:
        L.append("  {" + ",".join(str(x) for x in f) + "},")
    L.append("};")
    L.append("")
    L.append(f"const VocEnvelope {stem}_index[] PROGMEM = {{")
    for s, off, n, ns, ne in index:
        L.append(f'  {{"{s}", {off}, {n}, {ns}, {ne}}},')
    L.append("};")
    L.append(f"const int {stem}_count = {len(index)};")
    L.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(L))
    kb = args.out.stat().st_size/1024
    print(f"{args.out}  {len(index)} syllables  {total} frames  "
          f"{total*15} bytes of data  ({kb:.1f} kB of source)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
